version: "3.2"

services:
  user-service:
    image: user-service:1.0
    container_name: user-service
    ports:
      - "8000:8080"
    depends_on:
      - gateway-service
  question-service:
    image: question-service:1.0
    container_name: question-service
    ports:
      - "8100:8080"
    depends_on:
      - gateway-service
  tag-service:
    image: tag-service:1.0
    container_name: tag-service
    ports:
      - "8200:8080"
    depends_on:
      - gateway-service
  comment-service:
    image: comment-service:1.0
    container_name: comment-service
    ports:
      - "8300:8080"
    depends_on:
      - gateway-service
  answer-service:
    image: answer-service:1.0
    container_name: answer-service
    ports:
      - "8400:8080"
    depends_on:
      - gateway-service
  gateway-service:
    image: gateway-service:1.0
    container_name: gateway-service
    ports:
      - "9999:8080"
