version: "3.2"

services:
  user-service:
    image: user-service:1.0
    container_name: user-service
    ports:
      - "8091:8080"
    depends_on:
      - gateway-service
  question-service:
    image: question-service:1.0
    container_name: question-service
    ports:
      - "8100:8080"
    depends_on:
      - gateway-service
  gateway-service:
    image: gateway-service:1.0
    container_name: gateway-service
    ports:
      - "9999:8080"
