server:
  port: 8100
  address: 0.0.0.0
spring:
#  main:
#    lazy-initialization: true
#    allow-circular-references: true
  elasticsearch:
    uris: "http://36.26.69.161:9200"
#    username: xxxx
#    password: xxxx
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: true
  rabbitmq:
    host: 47.93.248.2
    port: 5672
    username: admin
    password: 123
    virtual-host: /
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: red-book-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
