server:
  port: 9999
spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # 注册登录服务
        - id: auth-service
          uri: lb://user-service
          predicates: #路由断言，判断请求是否符合规则
            - Path=/auth/**  # 判断请求路径
          filters:
            - name: IgnoreGlobalFilter  # 忽略全局过滤器
        # 用户服务
        - id: user-service
          uri: lb://user-service
          predicates: #路由断言，判断请求是否符合规则
            - Path=/user/**  # 判断请求路径
        # 问题服务
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/question/**
          filters:
            - name: IgnoreGlobalFilter  # 忽略全局过滤器
        # 标签服务
        - id: tag-service
          uri: lb://tag-service
          predicates:
            - Path=/tag/**
        # 回答服务
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/answer/**
          filters:
            - name: IgnoreGlobalFilter  # 忽略全局过滤器
        # 评论服务
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
          filters:
            - name: IgnoreGlobalFilter  # 忽略全局过滤器
      globalcors:
        add-to-simple-url-handler-mapping: true # 放行options请求
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            #            allowedOrigins: # 允许哪些网站的跨域请求
            #              - "http://www.scblogs.cn"
            #              - "http://127.0.0.1"
            allowedMethods: # 允许的跨域ajax请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 本次跨域检查的有效期
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: bridge-to-china-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
