server:
  port: 9999


spring:
#  main:
#    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 47.93.248.2:8848
      discovery:
        server-addr: 47.93.248.2:8848
        ip: 47.93.248.2
        port: 8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates: #路由断言，判断请求是否符合规则
            - Path=/user/**,/auth/**  # 判断请求路径
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/question/**
      globalcors:
        add-to-simple-url-handler-mapping: true # 放行options请求
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            #            allowedOrigins: # 允许哪些网站的跨域请求
            #              - "http://www.scblogs.cn"
            #              - "http://127.0.0.1"
            allowedMethods: # 允许的跨域ajax请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 本次跨域检查的有效期

