springdoc:
  swagger-ui:
    path: "user-service"
server:
  port: 8091
  address: 0.0.0.0
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
    main:
      allow-circular-references: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
  rabbitmq:
    host: 47.93.248.2
    port: 5672
    username: admin
    password: 123
    virtual-host: /
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: red-book-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: mall
  key:
    user: 'user'
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时
#secure:
#  ignored:
#    urls: #安全路径白名单
#      - /swagger-ui/
#      - /swagger-resources/**
#      - /**/v2/api-docs
#      - /**/*.html
#      - /**/*.js
#      - /**/*.css
#      - /**/*.png
#      - /favicon.ico
#      - /actuator/**
#      - /druid/**
#      - /admin/login
#      - /admin/register
#      - /admin/info
#      - /admin/logout
#      - /api/auth/**
#      - /api/**
