spring:
  datasource:
    url: jdbc:mysql://47.93.248.2:3306/btc_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: '0137989720'
  redis:
    #    host: localhost # Redis服务器地址
    #    database: 0 # Redis数据库索引（默认为0）
    #    port: 6379 # Redis服务器连接端口
    #    password: # Redis服务器连接密码（默认为空）
    #    timeout: 3000ms # 连接超时时间（毫秒）
    host: 36.26.69.161 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    #    password: '!Aa0137989720' # Redis服务器连接密码（默认为空）
    password: '123456' # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
  logging:
    level:
      root: info

  elasticsearch:
    uris: 36.26.69.161:9200


elasticsearch:
  http: "36.26.69.161:9200"

#Netty的一些配置
netty:
  timeout: 6000
  port: 9000
  #多端口绑定
  portSalve: 9001
