spring:
  cloud:
     nacos:
      server-addr: localhost:8848
      config:
        namespace: dev
        file-extension: yaml
      discovery:
        namespace: dev
        metadata:
          preserved.heart.beat.interval: 1000 #心跳间隔。时间单位:毫秒。心跳间隔
          preserved.heart.beat.timeout: 3000 #心跳暂停。时间单位:毫秒。 即服务端6秒收不到客户端心跳，会将该客户端注册的实例设为不健康：
          preserved.ip.delete.timeout: 3000 #Ip删除超时。时间单位:毫秒。即服务端9秒收不到客户端心跳，会将该客户端注册的实例删除：


