spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bridge_to_china?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "123456"
