minio:
  #minio部署的机器ip地址
  endpoint: http:/127.0.0.1:9000
  #minio使用的端口
  #  port: 9000
  #唯一标识的账户
  accessKey: admin
  #账户的密码
  secretKey: 123456
  #是否使用https
  #  secure: false
  #测试使用的桶名称
  defaultBucketName: test
