spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    main:
      allow-circular-references: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-file-size: 100MB
  logging:
    level:
      root: info
